### ISSUE TITLE
Certificate on us-east-2a.ipfs.tallylab.com has expired

### ISSUE THREAD

**Issue by MatthewSteeples** [tallylab/tallylab#24]
Referenced from js\api.js

I believe that some of these references (eg billing) will want removing. There looks to be some other pieces to do with taking backups of data, which I'm hoping either remain in some way or we can move to [orbit-db pinning](https://github.com/orbitdb/orbit-db-pinner) (so that users can take care of their own syncing / backups)

**Comment by skybondsor** [comment]
ATTN @aphelionz

**Comment by aphelionz** [comment]
On it! At the very least I can fix the cert on us-east-1 and then we can talk about moving to a pinner or community nodes, which is the ideal.

**Comment by aphelionz** [comment]
Certificate has been renewed, sorry for the inconvenience!
